Title="local"
# FixTime=true
CoinSymbol="DEV"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "info"
logConsoleLevel = "crit"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "data/chain.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
defCacheSize=128
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="data/datadir"
dbCache=64
isStrongConsistency=false
singleMode=true
batchsync=false
isRecordBlockSequence=true
isParaChain=false
enableTxQuickIndex=true
enableReExecLocal=true

[p2p]
port=13802
seeds=[]
enable=true
isSeed=true
serverStart=true
innerSeedEnable=false
useGithub=false
innerBounds=300
msgCacheSize=10240
driver="leveldb"
dbPath="data/datadir/addrbook"
dbCache=4
grpcLogFile="data/grpc.log"

[rpc]
jrpcBindAddr=":8801"
grpcBindAddr=":8802"
whitelist=["*"]
jrpcFuncWhitelist=["*"]
grpcFuncWhitelist=["*"]

[mempool]
name="timeline"
poolCacheSize=10240
minTxFee=100000
maxTxNumPerAccount=1000
maxTxFee=1000000000

[mempool.sub.timeline]
poolCacheSize=10240

[mempool.sub.score]
poolCacheSize=10240
timeParam=1      #时间占价格比例
priceConstant=10  #手续费相对于时间的一个的常量,排队时手续费高1e3的分数~=快1h的分数
pricePower=1     #常量比例

[mempool.sub.price]
poolCacheSize=10240

[consensus]
name="ticket"
minerstart=true
genesisBlockTime=1514533394
#d895355a456547d59bd3e9429bd0d1a3f491a2c4dc7009c72fcc3c0b7b4b3ade
genesis="1Eoxexw1T5VgawCg2EQLmc3ZuvWXGpfQNF"
minerExecs=["ticket", "autonomy"]

[mver.consensus]
fundKeyAddr = "1Ji3W12KGScCM7C2p8bg635sNkayDM8MGY"
powLimitBits="0x1f00ffff"
maxTxNumber = 1500

[mver.consensus.ticket]
coinReward = 5
coinDevFund = 3
ticketPrice = 1000
retargetAdjustmentFactor = 4
futureBlockTime = 15
targetTimespan = 2160
targetTimePerBlock = 15
ticketFrozenTime = 43200
ticketWithdrawTime = 172800
ticketMinerWaitTime = 7200

[consensus.sub.dpos]
delegateNum=1
blockInterval=2
continueBlockNum=12
blockNumToUpdateDelegate=200
registTopNHeightLimit=10
updateTopNHeightLimit=20

[consensus.sub.ticket]
genesisBlockTime=1559750400

[[consensus.sub.ticket.genesis]]
#3990969DF92A5914F7B71EEB9A4E58D6E255F32BF042FEA5318FC8B3D50EE6E8
minerAddr="1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs"
returnAddr="1CbEVT9RnM5oZhWMj4fxUrJX94VtRotzvs"
count=3000

[store]
name="kvmvccmavl"
driver="leveldb"
dbPath="data/datadir/mavltree"
dbCache=128
# store数据库版本
storedbVersion="2.0.0"

[store.sub.mavl]
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000
# 是否使能mavl数据载入内存
enableMemTree=true
# 是否使能mavl叶子节点数据载入内存
enableMemVal=true
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000
tkCloseCacheLen=100000

[store.sub.kvmvccmavl]
enableMVCCIter=true
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000
# 是否使能mavl数据载入内存
enableMemTree=true
# 是否使能mavl叶子节点数据载入内存
enableMemVal=true
# 缓存close ticket数目，该缓存越大同步速度越快，最大设置到1500000
tkCloseCacheLen=100000

[wallet]
minFee=100000
driver="leveldb"
dbPath="data/wallet"
dbCache=16
signType="secp256k1"

[wallet.sub.ticket]
minerdisable=false
minerwhitelist=["*"]

[wallet.sub.multisig]
rescanMultisigAddr=false

[exec]
isFree=false
minExecFee=100000
maxExecFee=1000000000
enableStat=false
enableMVCC=false
alias=["token1:token","token2:token","token3:token"]

[exec.sub.token]
saveTokenTxList=true
tokenApprs = [
        "1Eoxexw1T5VgawCg2EQLmc3ZuvWXGpfQNF"
]

[exec.sub.cert]
# 是否启用证书验证和签名
enable=false
# 加密文件路径
cryptoPath="data/authdir/crypto"
# 带证书签名类型，支持"auth_ecdsa", "auth_sm2"
signType="auth_ecdsa"

[exec.sub.relay]
genesis="1Eoxexw1T5VgawCg2EQLmc3ZuvWXGpfQNF"

[exec.sub.manage]
superManager=[
    "1Eoxexw1T5VgawCg2EQLmc3ZuvWXGpfQNF"
]

[exec.sub.paracross]
nodeGroupFrozenCoins=0
#平行链共识停止后主链等待的高度
paraConsensusStopBlocks=30000

[exec.sub.autonomy]
total="16htvcBNSEA7fZhAdLJphDwQRQJaHpyHTp"
useBalance=false

[health]
listenAddr=":8805"
checkInterval=5
unSyncMaxTimes=6