Title="user.p.testchain."
CoinSymbol="TEST"
EnableParaFork=true

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "info"
logConsoleLevel = "crit"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "data/chain.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = false
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
defCacheSize=128
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="memdb"
dbPath="data/paradatadir"
dbCache=64
isStrongConsistency=true
singleMode=true
batchsync=false
isRecordBlockSequence=false
isParaChain = true
enableTxQuickIndex=true
# 升级storedb是否重新执行localdb，主链升级不需要开启，平行链升级需要开启
enableReExecLocal=true

[p2p]
seeds=[]
enable=false
isSeed=false
serverStart=true
innerSeedEnable=false
useGithub=false
innerBounds=300
msgCacheSize=10240
driver="memdb"
dbPath="data/paradatadir/addrbook"
dbCache=4
grpcLogFile="data/grpc.log"

[rpc]
# 避免与主链配置冲突
jrpcBindAddr=":8901"
grpcBindAddr=":8902"
whitelist=["*"]
jrpcFuncWhitelist=["*"]
grpcFuncWhitelist=["*"]
mainnetJrpcAddr= "http://127.0.0.1:8801"

[mempool]
name="para"
poolCacheSize=10240
minTxFee=100000
maxTxNumPerAccount=10000

[consensus]
name="para"
genesisBlockTime=1565193600
#5517880dbfd29fb50755bb6ec78428a02b5cc71cd7ae2154216959cf637be536
genesis="1EA1rA8X1FkhnzvAKyZDeTFSZZY533N6Jx"
minerExecs=["paracross"]    #配置挖矿合约

[mver.consensus]
fundKeyAddr = "1JYHqyPQxTNgP7sqwT87XyefKVhLA8faBW"
powLimitBits = "0x1f00ffff"
maxTxNumber = 1600      #160

[mver.consensus.paracross]
coinReward=5
coinDevFund=3

[consensus.sub.para]
#此处IP改成实际的地址
ParaRemoteGrpcClient = "127.0.0.1:8802"
#指定从主链某高度的区块开始同步
startHeight=7800
#打包时间间隔，单位秒
writeBlockSeconds=5
#创世地址额度
genesisAmount=6000000000
#验证账户，验证节点需要配置自己的账户，并且钱包导入对应种子，非共识节点留空
#authAccount="1EA1rA8X1FkhnzvAKyZDeTFSZZY533N6Jx"
#主链支持平行链共识tx分叉高度，需要和主链保持严格一致
MainForkParacrossCommitTx=1
MainBlockHashForkHeight=1
#主链开启循环检查共识交易done的fork高度,需要和主链保持严格一致
MainLoopCheckCommitTxDoneForkHeight=1
#平行链自共识开启对应的主链高度，需要大于等于MainForkParacrossCommitTx，-1 不开启
MainParaSelfConsensusForkHeight=-1

#主链每隔几个没有相关平行链交易的区块，平行链上打包空区块，缺省从平行链blockHeight=0开始，依次增长，空块间隔不能为0
[[consensus.sub.para.emptyBlockInterval]]
blockHeight=0
interval=50

[store]
name="kvmvccmavl"
driver="leveldb"
storedbVersion="2.0.0"
dbPath="data/paradatadir/mavltree"
dbCache=128
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000

[store.sub.mavl]
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000
enableMemTree=true
enableMemVal=true

[store.sub.kvmvccmavl]
enableMVCCIter=true
enableMavlPrefix=false
enableMVCC=false
enableMavlPrune=false
pruneHeight=10000
enableMemTree=true
enableMemVal=true

[wallet]
minFee=100000
driver="leveldb"
dbPath="data/parawallet"
dbCache=16
signType="secp256k1"
minerdisable=true

[exec]
isFree=true
minExecFee=100000
enableStat=false
enableMVCC=false

[exec.sub.manage]
superManager=[
    "1EA1rA8X1FkhnzvAKyZDeTFSZZY533N6Jx"
]

[exec.sub.token]
saveTokenTxList=true
tokenApprs = [
	"1EA1rA8X1FkhnzvAKyZDeTFSZZY533N6Jx"
]

[exec.sub.paracross]
#平行链自共识停止n个空块的对应主链高度后，超级账户可以直接参与投票,这个高度只在主链有效
paraConsensusStopBlocks=30000

[exec.sub.autonomy]
total="16htvcBNSEA7fZhAdLJphDwQRQJaHpyHTp"
useBalance=false

[health]
listenAddr=":8855"
checkInterval=5
unSyncMaxTimes=6

[fork.system]
ForkChainParamV1= 0
ForkCheckTxDup=0
ForkBlockHash= 1
ForkMinerTime= 0
ForkTransferExec=0
ForkExecKey=0
ForkTxGroup=0
ForkResetTx0=0
ForkWithdraw=0
ForkExecRollback=0
ForkCheckBlockTime=0
ForkTxHeight=0
ForkTxGroupPara=0
ForkChainParamV2=0
ForkMultiSignAddress=0
ForkStateDBSet=0
ForkLocalDBAccess=0
ForkBlockCheck=0
ForkBase58AddressCheck=0
ForkEnableParaRegExec=0
ForkCacheDriver=0
ForkTicketFundAddrV1=-1

[fork.sub.coins]
Enable=0

[fork.sub.ticket]
Enable=0
ForkTicketId =0
ForkTicketVrf =0

[fork.sub.retrieve]
Enable=0
ForkRetrive=0
ForkRetriveAsset=0

[fork.sub.hashlock]
Enable=0
ForkBadRepeatSecret=0

[fork.sub.manage]
Enable=0
ForkManageExec=0

[fork.sub.token]
Enable=0
ForkTokenBlackList= 0
ForkBadTokenSymbol= 0
ForkTokenPrice=0
ForkTokenSymbolWithNumber=0
ForkTokenCheck= 0

[fork.sub.trade]
Enable=0
ForkTradeBuyLimit= 0
ForkTradeAsset= 0
ForkTradeID = 0
ForkTradeFixAssetDB = 0
ForkTradePrice = 0

[fork.sub.paracross]
Enable=0
ForkParacrossWithdrawFromParachain=0
ForkParacrossCommitTx=0
ForkLoopCheckCommitTxDone=0

[fork.sub.relay]
Enable=0

[fork.sub.privacy]
Enable=0

[fork.sub.multisig]
Enable=0

[fork.sub.unfreeze]
Enable=0
ForkTerminatePart=0
ForkUnfreezeIDX= 0

[fork.sub.store-kvmvccmavl]
ForkKvmvccmavl=0